### ISSUE TITLE
[Question] Where can i find an exemple how to load .osm file?

### ISSUE THREAD

**Issue by jlstanus** [gboeing/osmnx-examples#10]
In the [readme ](https://github.com/gboeing/osmnx) you explain  it's possible to load .osm file.

I'didn't find in the doc or in the exemple how to do.

thanks for this work!

**Comment by gboeing** [comment]
Here you go: https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.core.graph_from_file

**Comment by jlstanus** [comment]
Didn't seen it because i didn't check all the core modules sorry.

Thank you for information.

Cordialement,

Jean-Louis Stanus


----


Jean-louis Stanus
[image: https: //]about.me/jl.stanus
<https://about.me/jl.stanus?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>

☎ +32 473761482



Le mar. 10 juil. 2018 à 18:17, Geoff Boeing <notifications@github.com> a
écrit :
