### ISSUE TITLE
Problem viewing 11-plot-routes-folium-web-map

### ISSUE THREAD

**Issue by eavrunin** [gboeing/osmnx-examples#11]
When I look at the folium example notebook, none of the IFrame outputs displays anything.  Am I missing something?  Is there a problem with the html files?

**Comment by gboeing** [comment]
GitHub itself doesn't render IFrames, so you won't see anything online. But the example works fine on my computer. If it doesn't on yours when you run it locally, please open an issue directly in the OSMnx repo: https://github.com/gboeing/osmnx/issues

**Comment by eavrunin** [comment]
Oh, I didn't realize it wasn't expected to show here.  My IPython installation is messed up at the moment, so I was only looking online (GitHub and Jupyter nbviewer).  Thanks!
