### ISSUE TITLE
Connection error (access from behind the proxy)

### ISSUE THREAD

**Issue by sbushmanov** [gboeing/osmnx-examples#21]
The simple notebook  `00-osmnx-features-demo.ipynb` is not working due to connection error:

```
G = ox.graph_from_place('Piedmont, California, USA', network_type='drive')
fig, ax = ox.plot_graph(G)

ConnectionError: HTTPConnectionPool(host='overpass-api.de', port=80): Max retries exceeded with url: /api/interpreter (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd250542d30>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
```

**Comment by gboeing** [comment]
@sbushmanov Errno 101 usually results from network configuration or port blocking on the client side. As you can see, the [overpass api](https://overpass-api.de/api/status) is up right now and I can confirm your code snippet is working fine this morning on my network.

**Comment by sbushmanov** [comment]
Is there a way to access the service via proxy?
