### ISSUE TITLE
osmnx simplify_graph does not remove all intermediate nodes that are not intersections

### ISSUE THREAD

**Issue by MalikOvaiz** [gboeing/osmnx-examples#29]
I have used method simplify_graph for network simplification, there are still many intermediate nodes that do not have interactions.  

```
G3 = ox.graph_from_file( osm_simplified_file, bidirectional=False,simplify=False, retain_all=False, name='unnamed')
G3 = ox.simplify_graph(G3, strict=False)
G3 = ox.remove_isolated_nodes(G3);
G3 = ox.get_largest_component(G3,strongly=True);
ox.plot_graph(G3,......)
```

Is there anything missing in above code? 
please check following links for details
[https://stackoverflow.com/questions/59184047/osmnx-simplify-graph-does-not-remove-all-nodes-that-are-not-intersections](url)

**Comment by gboeing** [comment]
Automatically closing. See contributing guidelines.
