### ISSUE TITLE
Different lengths of basic and extended stats dictionary columns

### ISSUE THREAD

**Issue by RockyCD** [gboeing/osmnx-examples#3]
# Possibility of Error or Misunderstanding of how "Calculate basic street network measures (topological and metric)" works
![image](https://user-images.githubusercontent.com/19784272/29237341-80d19174-7eea-11e7-9fd1-38c021341282.png)

This is from notebook ["06-example-osmnx-networkx.ipynb](06-example-osmnx-networkx.ipynb) 

"Use OSMnx to analyze a NetworkX street network, including routing""

In the example, the length of the dataframe is 30 columns. 

1. Is that the standard? 
2. Should other places, if they exist as a polygon,  be consistent in polygon length, if I am using the same arguments? 

I have ran multiple tests on different cities, and I either get 26 or 28 columns, respectively. 

The only two arguments that I called are G and area from these [basic stats docs](http://osmnx.readthedocs.io/en/latest/osmnx.html#module-osmnx.stats)

I am trying to see where the error is because if I have the same argument for every place and I know the shapes exist, why would they have different column lengths? 

      `stats = ox.basic_stats(G, area=area)
        for k, count in stats['streets_per_node_counts'].items():
            stats['int_{}_count'.format(k)] = count
        for k, proportion in stats['streets_per_node_proportion'].items():
            stats['int_{}_prop'.format(k)] = proportion`

The only solution I can think of why I may have different columns is how I am writing it to a csv,
```
        que = pd.DataFrame(pd.Series(stats)).T
        with open(file_name +'.csv', 'w') as f:
            que.to_csv(f, header=False,index=False,encoding='utf-8')
```

Full code for clarity

```
for value in df.Name:
        place = value
        gdf = ox.gdf_from_place(place)
        area = ox.project_gdf(gdf).unary_union.area
        G = ox.graph_from_place(place, network_type='drive_service')
        stats = ox.basic_stats(G, area=area)
        for k, count in stats['streets_per_node_counts'].items():
            stats['int_{}_count'.format(k)] = count
        for k, proportion in stats['streets_per_node_proportion'].items():
            stats['int_{}_prop'.format(k)] = proportion
        # delete the no longer needed dict elements
        del stats['streets_per_node_counts']
        del stats['streets_per_node_proportion']
        file_name = str(counter)
        que = pd.DataFrame(pd.Series(stats)).T
        with open(file_name + '.csv', 'w') as f:
            que.to_csv(f, header=False,index=False,encoding='utf-8')
        del stats
        del place
        del area
        del gdf
       time.sleep(1000)
```

**Comment by gboeing** [comment]
Which columns are missing when you get fewer than the example?

**Comment by RockyCD** [comment]
> Which columns are missing when you get fewer than the example?
See this is the problem, I did not write headers to the file.

If you like I have a list of cities and I can give you the respective column lengths if that helps?
Otherwise, I can run it  again and write headers for each file.

**Comment by gboeing** [comment]
Could you provide a full working example that I can run from scratch to reproduce? List of missing column names would be helpful too.

**Comment by RockyCD** [comment]
Forgive me, I may have mis-worded what I meant, by "missing columns"

I thought that after running through 188 places, getting different column lengths was odd.
I thought that their would be place holder values for each column name inside the dict, but I could be wrong.
```
CLength         # of Occurrences
26                       86
28                       78
30                       20
32                        4
Name: Column_Length, dtype: int64
```

The fix for me,( I hope) is to print out the headers of one file for each respective group.


> Could you provide a full working example that I can run from scratch to reproduce? List of missing column names would be helpful too.

I thought I already did above. 
```
for value in df.Name:
        place = value
```
Value is a name of a city or place that has a shape file.
Sure, I could give you a list of a few places that give me different column outputs when I write them to a csv.

**Comment by RockyCD** [comment]
[geoff.txt](https://github.com/gboeing/osmnx-examples/files/1220637/geoff.txt)

**Comment by RockyCD** [comment]
I am closing this as a non-issue, from what I can tell, it relates to the size of each place.
circuity_avg		circuity_avg
count_intersections		count_intersections
edge_density_km		edge_density_km
edge_length_avg		edge_length_avg
edge_length_total		edge_length_total
int_0_count		int_0_count
int_0_prop		int_0_prop
int_1_count		int_1_count
int_1_prop		int_1_prop
int_2_count		int_2_count
int_2_prop		int_2_prop
int_3_count		int_3_count
int_3_prop		int_3_prop
int_4_count		int_4_count
int_4_prop		int_4_prop
int_5_count		intersection_density_km
int_5_prop		k_avg
intersection_density_km		m
k_avg		n
m		node_density_km
n		self_loop_proportion
node_density_km		street_density_km
self_loop_proportion		street_length_avg
street_density_km		street_length_total
street_length_avg		street_segments_count
street_length_total		streets_per_node_avg
street_segments_count		
streets_per_node_avg

**Comment by gboeing** [comment]
@RockyCD yes. The stats functions return the exact number of elements as specified in the documentation. However, their sub-dicts that contain counts of intersection types and proportions of intersection types (for instance) will different numbers of keys. In the example above, one city has an intersection with 5 streets connected to it. The other city does not. Hence the different keys. You got different numbers of columns because you unpack the dicts into flat structures in the code snippet you ran.

**Comment by RockyCD** [comment]
@gboeing That is what I thought. Thank you for your time! What you have built is extremely impressive.( At least to me)
