### ISSUE TITLE
Install troubleshooting

### ISSUE THREAD

**Issue by jaimebayes** [gboeing/osmnx-examples#32]
Hi, 

I am having problems to install osmnx package on colab jupyter notebook.

When I use pip I got this error:
`!pip install osmnx`
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

When I use apt, I got this:
`!apt install osmnx`
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package osmnx

Why it is this happening? any advice?, 

Thanks in advance, JL

**Comment by gboeing** [comment]
Per the new issue template:

> This issue tracker is for proposing new examples or specific changes to existing examples. Please ask "how-to" questions on https://stackoverflow.com/ instead.

For installation instructions, read the docs: https://osmnx.readthedocs.io/
