### ISSUE TITLE
[Question] would it be possible to show a trajectory (moving object) with Osmnx (stream plotting)

### ISSUE THREAD

**Issue by mohsenD98** [gboeing/osmnx-examples#49]
plotting in osmnx is on images, but is it possible to plot a trajectory (for example a car) that is dynamically moving ?
if it is possible what is the efficient approach ? thank you

**Comment by gboeing** [comment]
Please reread the contributing guidelines and new issue template for suggestions on where to ask how-to usage questions.

**Comment by mohsenD98** [comment]
could you please share the contributing guidelines link.   
thank you.
