### ISSUE TITLE
error in notebook 08

### ISSUE THREAD

**Issue by mengluchu** [gboeing/osmnx-examples#56]
I got an error when running notebook 08 using the environment from the yml provided in the repository: 

In chunk 2
G = ox.graph_from_place('Piedmont, California', network_type='drive')

ValueError: Assigning CRS to a GeoDataFrame without a geometry column is not supported. Use GeoDataFrame.set_geometry to set the active geometry column.

**Comment by gboeing** [comment]
What version of OSMnx are you using? Ensure it is the latest (v1.2.x)
