### ISSUE TITLE
Add Clustering Example by Network Distance

### ISSUE THREAD

**Issue by miili** [gboeing/osmnx-examples#58]
Thanks for this comprehensive library.

I found and old example of yours, which interesting for our organization of field work.

https://github.com/gboeing/network-clustering/blob/main/network-clustering-simple.ipynb

I would love to see this as part of this repo. Adapted to the newer API.

Thanks and best wishes,

Miili

**Comment by gboeing** [comment]
@miili I'll aim to add this prior to the release of OSMnx v2.0

**Comment by gboeing** [comment]
Example added in #97.
