### ISSUE TITLE
NetworkXNotImplemented in 08-example-line-graph

### ISSUE THREAD

**Issue by philippks** [gboeing/osmnx-examples#6]
Example [08-example-line-graph](https://github.com/gboeing/osmnx-examples/blob/master/notebooks/08-example-line-graph.ipynb) seems not to work anymore.

When [executing with mybinder.org](https://hub.mybinder.org/user/philippks-osmnx-examples-dmkudmak/notebooks/notebooks/08-example-line-graph.ipynb), I get an error:

![image](https://user-images.githubusercontent.com/8806985/37284326-69aa036a-25fb-11e8-90ef-62092f530edf.png)

Did something change or am I missing something?

**Comment by gboeing** [comment]
@philippks everything should be working fine. That notebook just run without problem on my machine. Make sure your packages are all up-to-date and try again? If you're still having trouble, please open an issue in the OSMnx repo with details about your platform, package versions, etc and we'll troubleshoot.

**Comment by philippks** [comment]
Thank you for your fast reply @gboeing.

osmnx 0.7.3 depends on networkx 2.1, where [this PR](https://github.com/networkx/networkx/pull/2814) wrongly added the annotation `@not_implemented_for('multigraph')` to the method `line_graph`. This change was corrected with [this PR](https://github.com/networkx/networkx/pull/2883) (which is not yet released).

Therefore, [the notebook](https://github.com/gboeing/osmnx-examples/blob/master/notebooks/08-example-line-graph.ipynb) only executes on my machine when **downgrading** osmnx to 0.7.1.

It is strange that the notebook works fine on your machine (do you've the newest versions installed?). Feel free to close this issue, but I believe the problem is not solved until networkx is upgraded to 2.2.

**Comment by gboeing** [comment]
@philippks thanks for tracking that down! That explains it... I had run that notebook just now using the nx 2.2 release candidate.

Would you like to add a comment to that notebook cell regarding the version number needed, given this bug, and open a PR?

**Comment by philippks** [comment]
:+1: I created a PR. Thanks for your great work btw.

**Comment by gboeing** [comment]
@philippks thanks!

**Comment by dvu4** [comment]
Hi Geoff, 

can we plot the colored  edges with closeness centralities in the folium ? 

I convert multigraph to line_graph in order to compute edge closeness centrality

`GG = nx.Graph()

for node, neighbors in G.adjacency(): # Return (node, adjacency dict) tuples for all nodes.
    for neighbor, edict in neighbors.items():
        GG.add_edge(node, neighbor)

edge_centrality = nx.closeness_centrality(nx.line_graph(GG))` 

But number of edges in multigraph is different from those in line_graph
