### ISSUE TITLE
AttributeError: module 'osmnx' has no attribute 'utils_graph' in 00-osmnx-features-demo.ipynb

### ISSUE THREAD

**Issue by keyur077** [gboeing/osmnx-examples#62]
Getting below issue when tried to execute the code mentioned in [00-osmnx-features-demo.ipynb](https://github.com/gboeing/osmnx-examples/blob/main/notebooks/00-osmnx-features-demo.ipynb)

I am trying to execute that code in my local notebook & came across below error

<img width="914" alt="Screenshot 2023-01-05 at 4 42 06 PM" src="https://user-images.githubusercontent.com/9676612/210767175-c4339bd4-762a-4b1d-9995-9b0d469f03a3.png">

I am not sure if this issue belongs to this repo or [OSMnx repo's issue tracker](https://github.com/gboeing/osmnx).

**Comment by gboeing** [comment]
Do you have a file called osmnx.py in your working directory? What is the output of just running the line `ox` in a cell?

**Comment by gboeing** [comment]
I'm going to close this here, but if the issue persists, please open in OSMnx's issue tracker and provide all the info requested in the new issue template there. Thanks.
