### ISSUE TITLE
examples update needed

### ISSUE THREAD

**Issue by cryptid11** [gboeing/osmnx-examples#63]
https://github.com/gboeing/osmnx-examples/blob/v0.11/notebooks/06-example-osmnx-networkx.ipynb

im following that but is bit out of date:

gdf_from_place is now geocode_to_gdf (https://github.com/gboeing/osmnx/pull/506/commits/e039471093c7b573c637e7e3462f16a178a079d1)
but extended_stats is just deprecated and i dont see any new function replacing it, i'll wait for it to be updated, thanks
btw amazing work! :D

**Comment by gboeing** [comment]
You are using the `v0.11` tag. Just use the main branch for the up to date version.

**Comment by cryptid11** [comment]
what a shame, i dont even know how do i stumble there! thanks a lot for patience and again my compliments!
