### ISSUE TITLE
Problem to install at anaconda python 3.6 in ubuntu 16.04

### ISSUE THREAD

**Issue by Isaquedanielre** [gboeing/osmnx-examples#9]
Hi, I had install osmnx at python 3.6 anaconda in ubuntu 16.04 and when I try to load the package, the message of error is:

      import osmnx as ox

      ox.graph_from_address('Brasilia, Distrito Federal', network_type='drive')

      Traceback (most recent call last):
    File "/home/isaque/Continuum/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
       exec(code_obj, self.user_global_ns, self.user_ns)
        File "<ipython-input-3-071b4c6fb9a2>", line 1, in <module>
             ox.graph_from_address('Brasilia, Distrito Federal', network_type='drive')
         AttributeError: module 'osmnx' has no attribute 'graph_from_address'

     The strange part is when I try to verify the version, it returns the version is "1.0.0", when in fact your version is 0.8 (look at picture):

![osmnxproblem](https://user-images.githubusercontent.com/5652407/39900771-88ccc958-549a-11e8-870a-a2f5a405cf87.jpg)

I try install by pip, by anaconda, using direct download from github. I don't know to fix it. Any idea?

**Comment by gboeing** [comment]
There's certainly something wrong with your OSMnx installation (as there is no version 1.0) and possibly with your Anaconda installation. Can you uninstall Anaconda and reinstall it, then install OSMnx? Can you install OSMnx in a virtual environment? Please try these then send the results of running `conda info` and `conda list osmnx`.

**Comment by gboeing** [comment]
If this is an ongoing conda installation problem please open an issue at https://github.com/conda-forge/osmnx-feedstock
